Improve debug and printing of `Tensor` and `ReadonlyTensor`
tensorflow/rust pull request #363
Opened 2022-07-01 09:32 UTC by jackos

This adds debug and alternate debug of the values in a tensor, which improves dev experience when experimenting with operations, expressions, and eager raw_ops on tensors.

### Standard Debug
```rust
let values: Vec<u16> = (1..9).collect(); 
let tensor = Tensor::new(&[2, 2, 2]).with_values(&values)?;

println!("{tensor:?}");
```
```plaintext
Tensor<u16> { values: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype: uint16, shape: [2, 2, 2]}
```
### Alternate Debug (pretty)
```rust
dbg!(tensor);
```
```plaintext
[examples/show.rs:10] &tensor = Tensor<u16> {
    values: [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ],
    dtype: uint16,
    shape: [2, 2, 2]
}
```
It also adds a maximum to how many elements are printed, which works across printing and debugging to only display a `...` if the maximum elements are exceded:
### Print max elements exceeded
```bash
TF_RUST_DISPLAY_MAX=5
```
```rust
dbg!(tensor);
```
```plaintext
[examples/show.rs:11] &tensor = Tensor<u16> {
    values: [
        [[1, 2], [3, 4]],
        [[5, ...], ...]
    ],
    dtype: uint16,
    shape: [2, 2, 2]
}
```

```rust
println!("{tensor}");
```
```plaintext
[[[1, 2], [3, 4]], [[5, ...], ...]]
```

2022-07-05 04:00 UTC, adamcrume commented
This looks useful, but I'm not convinced that truncating the tensors is the best behavior.  `println!("{:?}, vec![0.0; 10000])` prints everything, for example.

2022-07-05 06:45 UTC, jackos commented
> This looks useful, but I'm not convinced that truncating the tensors is the best behavior. `println!("{:?}, vec![0.0; 10000])` prints everything, for example.

Do you mean just for printing or debugging as well?

The intention was to follow the way the Python version works by guarding against a huge amount of data being printed to someone unsuspecting, but if you want it can be defaulted to off and turned on via setting a limit on the environment variable? Makes sense to follow normal Rust behavior.

2022-07-07 04:25 UTC, adamcrume requested changes

2022-07-07 04:25 UTC, adamcrume commented on src/eager/readonly_tensor.rs
> +impl<T: TensorType> Debug for ReadonlyTensor<T> {
ReadonlyTensor could use a Display impl, too, to keep it consistent with Tensor.

2022-07-07 04:25 UTC, adamcrume commented on src/eager/readonly_tensor.rs
> +        let dtype = self.data_type().to_string().to_lowercase();
There's no need to convert it to lowercase.  The case will match the cases of the DataType enum.

2022-07-07 04:25 UTC, adamcrume commented on src/lib.rs
> +    fn tensor_debug() {
We also need to test scalar tensors and zero-element tensors.

2022-07-07 04:25 UTC, adamcrume commented on src/lib.rs
> +                "Tensor<i32> { values: [1, 2, 3, 4, 5, 6, 7, 8], dtype: int32, shape: [8]}",
This format has spaces around the opening curly brace, but not the last one, which is inconsistent.

2022-07-07 04:25 UTC, adamcrume commented on src/lib.rs
> +        test_debug_i32_pretty(values, shape, pretty)
It'd be a lot easier to verify that these tests are testing the right thing if `pretty` contained the entire string verbatim, i.e. inline `test_debug_i32_pretty` and don't format or concatenate the expected strings in the tests.

2022-07-07 04:25 UTC, adamcrume commented on src/lib.rs
> +
The "pretty" format also needs to test scalar and zero-element tensors.

2022-07-11 01:08 UTC, jackos commented
@adamcrume thanks for the review, have fixed all of your comments

2022-07-14 04:10 UTC, adamcrume requested changes

2022-07-14 04:10 UTC, adamcrume commented on src/lib.rs
> +        let tensor = Tensor::<f32>::new(&[0, 0]);
To test for the bug I mentioned above, this could use a shape like [0, 10].

2022-07-14 04:10 UTC, adamcrume commented
Just a few minor issues to resolve, and this'll be ready.

2022-07-14 12:00 UTC, jackos commented on src/lib.rs
> +    let elements: u64 = dims.iter().sum();
Great point didn't think about that, I went with `if tensor.is_empty()`

2022-07-14 12:07 UTC, jackos commented
> Just a few minor issues to resolve, and this'll be ready.
Great thanks fixed the errors

2022-07-30 23:19 UTC, adamcrume commented
Sorry for the delay!  Looks good, and thanks!

2022-07-30 23:19 UTC, merged