Moving runtime bindings into their own crate
tensorflow/rust pull request #382
Opened 2022-09-26 23:35 UTC by brianjjones

The runtime bindings have no use for the the build-dependencies of tensorflow-sys, nor the build.rs. So to avoid pulling in those dependencies, and hopefully to keep things cleaner, I'd like to move them into their own crate.

2022-10-13 16:47 UTC, brianjjones commented
Hi @adamcrume , could I get some feedback on this when you get a chance? Thanks.

2022-10-28 03:56 UTC, adamcrume requested changes
RELEASING.md needs to be updated.

2022-10-28 03:56 UTC, adamcrume commented on tensorflow-sys-runtime/generate_bindgen_rs.sh
> +echo } >> src/runtime_linking/c_api.rs
All the runtime bits should be removed from tensorflow-sys/generate_bindgen_rs.sh.

2022-10-28 03:57 UTC, adamcrume commented
Sorry for the delay!

2022-10-28 21:07 UTC, brianjjones commented
@adamcrume Thanks for the review. I've updated the PR with the requested changes, let me know if there's anything else.

2022-10-29 23:30 UTC, merged

2022-10-29 23:31 UTC, adamcrume commented
Thanks!

2022-10-31 18:41 UTC, brianjjones commented
@adamcrume Great, thanks for that. Any idea when I can expect a new version to be pushed to crates.io?